In [1]:
import numpy as np

## 1.如何垂直堆叠两个数组？
####  输入：
#### a = np.arange(10).reshape(2,-1)
#### b = np.repeat(1, 10).reshape(2,-1)
#### 期望输出：
#### > array([[0, 1, 2, 3, 4],
#### > [5, 6, 7, 8, 9],
#### > [1, 1, 1, 1, 1],
#### > [1, 1, 1, 1, 1]])

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 2. 在不使用硬编码的前提下，如何在 NumPy 中生成自定义序列？
#### 问题：在不使用硬编码的前提下创建以下模式。仅使用 NumPy 函数和以下输入数组 a。
#### 输入：
#### a = np.array([1,2,3])`
####  期望输出：
#### > array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [52]:
a = np.array([1,2,3])

a1 = np.stack((a,a,a),axis=1)
a2=np.tile(a,3)
a3=np.hstack((a1))
np.hstack((a3,a2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 3.如何从一个数组中移除与另一个数组重复的项？
#### 问题：从数组 a 中移除出现在数组 b 中的所有项。
#### 输入：
####  a = np.array([1,2,3,4,5])
####  b = np.array([5,6,7,8,9])
####  期望输出：
####  array([1,2,3,4])

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# np.array(list(set(a)-set(b))) 

array([1, 2, 3, 4])

## 4. 如何获取两个数组匹配元素的位置？
#### 问题：获取数组 a 和 b 中匹配元素的位置。
#### 输入：
#### a = np.array([1,2,3,2,3,4,3,4,5,6])
#### b = np.array([7,2,10,2,7,4,9,4,9,8])
#### 期望输出：
#### > (array([1, 3, 5, 7]),)

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
condition = np.equal(a,b)
np.where(condition)

(array([1, 3, 5, 7], dtype=int64),)

## 5. 如何基于两个或以上条件过滤 NumPy 数组？
#### 问题：过滤 iris_2d 中满足 petallength（第三列）> 1.5 和 sepallength（第一列）< 5.0 的行。
#### Input
#### url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#### iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# iris_2d=np.array([[1.6,1.5,1.5,1.5],[5,5,4.5,5],[1.2,1.2,5.6,3]])
# print(iris_2d)
# sepallength=iris_2d[0:][:,[0]] #第一列
# petallength= iris_2d[0:][:,[2]] #第三列
# print(sepallength)
# print(petallength)
# less5 = sepallength[sepallength<5.0] 
# print(less5)
# greater1=petallength[petallength >1.5]
# print(greater1)
# print('-------------------')
# value = np.logical_and(less5,greater1)
# print(np.where(value))
# greater1 = np.greater(petallength,1.5)
# condition = np.logical_and(less5,greater1)
# iris_2d[ np.where(condition)]

# a=iris_2d[...,[2]]>1.5
# b=iris_2d[...,[0]]<5.0
# c=np.where(a&b,np.nan,iris_2d)
# data=c[~np.isnan(c)].reshape(-1,4)
# print(data)

con_a= iris_2d[:,2]>1.5 #第三列大于1.5的数
con_b=iris_2d[:,0]<5.0 #第一列
iris_2d[con_a&con_b]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## 6. 如何在 NumPy 数组中找出缺失值的位置？
#### 问题：在 iris_2d 的 sepallength（第一列）中找出缺失值的数目和位置。
#### Input
#### url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#### iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
#### iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [24]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# a = iris_2d
# index=np.where(np.isnan(a))[1]
# print(len(index))
position=np.where(np.isnan(iris_2d[:,0]))
position[0].size


4

## 如何归一化数组，使值的范围在 0 和 1 之间？
#### 问题：创建 iris sepallength 的归一化格式，使其值在 0 到 1 之间。
#### 输入：
#### url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#### sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
# (sepallength-np.min(sepallength))/(np.max(sepallength)-np.min(sepallength))
np.exp(sepallength)/sum(np.exp(sepallength))

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814