In [1]:
import numpy as np

In [5]:
# a = np.arange(10).reshape(2,-1)
# b = np.repeat(1, 10).reshape(2,-1)
# print(a)
# print(b)
# np.vstack([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# a = np.array([1,2,3])
# end=np.tile(a,[3,1]).reshape(-1) # 1 2 3 1 2 3 1 2 3
# start=np.tile(a.reshape(3,-1),3).reshape(-1) #[1, 1, 1, 2, 2, 2, 3, 3, 3]
# start=np.repeat(a,3)
# np.hstack([start,end])


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# np.array(list(set(a)-set(b)))
# np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


In [41]:
# 过滤 iris_2d 中满足 petallength（第三列）> 1.5 和 sepallength（第一列）< 5.0 的行。
# url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# con_a=iris_2d[:,2]>1.5
# con_b=iris_2d[:,0]<5.0
# iris_2d[con_a & con_b]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [51]:
# 在 iris_2d 的 sepallength（第一列）中找出缺失值的数目和位置
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# position=np.where(np.isnan(iris_2d[:,0]))
# num=position[0].size

4

In [59]:
# 创建 iris sepallength 的归一化格式，使其值在 0 到 1 之间。
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
# 归一化
# (sepallength-np.min(sepallength))/(np.max(sepallength)-np.min(sepallength))
# softmax() 
# np.exp(sepallength)/sum(np.exp(sepallength))


array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814